### ISSUE TITLE
[BUG] Type mismatch between reported and actual type of Blurhash Component

### ISSUE THREAD

**Issue by goleary** [mrousavy/react-native-blurhash#109]
# Bug
[The types](https://github.com/mrousavy/react-native-blurhash/blob/d4271749fb2c809a61bf6ad11905e6b83a82378b/index.d.ts#L68) for `Blurhash` report that it is a class component.

The [actual exported component](https://github.com/mrousavy/react-native-blurhash/blob/d4271749fb2c809a61bf6ad11905e6b83a82378b/index.js#L29) is a functional one.

My IDE reports that Blurhash is a class component and I was very confused why I was getting runtime errors reporting that I couldn't use a functional component.

# Environment

**Additional context**

```json
"react": 16.13.1
"react-native": 0.63.2,
"react-native-blurhash": 1.0.28
```

**Comment by mrousavy** [comment]
Oh yeah, for some reason I changed that.. I'm going to leave the types as they are, and convert the component back to a class component.

**Comment by mrousavy** [comment]
Fixed in https://github.com/mrousavy/react-native-blurhash/commit/bd440c42fb1555a7781c97436f6bea288d8acbe5. Thanks for reporting! 👋

**Comment by goleary** [comment]
Unreal, thanks for quickly taking care of it!
