### ISSUE TITLE
How to use with expo: requireNativeComponent BlurhashView was not found in the UIManager

### ISSUE THREAD

**Issue by max-frai** [mrousavy/react-native-blurhash#124]
Hello, I'm using latest expo sdk. After:
`npm i react-native-blurhash`

I just try to use it:
```
import { Blurhash } from "react-native-blurhash";
<Blurhash blurhash={...}  />
```

But get error:

<img width="396" alt="Screenshot 2021-07-27 at 10 53 03" src="https://user-images.githubusercontent.com/24208746/127117303-fa576ca8-af2b-4d09-b402-b6028686b94d.png">

**Comment by mrousavy** [comment]
Do I need to add a config plugin even if there's nothing in it? cc @EvanBacon

**Comment by EvanBacon** [comment]
Ya packages that are not in Expo Go cannot be used in the Expo Go app (including this one). You'll need to create a custom Expo development client or build the project locally with the [Expo run commands](https://blog.expo.io/introducing-expo-run-commands-835ae8da4813).
