### ISSUE TITLE
[BUG] Compilation error with React Native 0.65

### ISSUE THREAD

**Issue by beetlebum** [mrousavy/react-native-blurhash#125]
I believe RN 0.65 updates the version of Fresco embedded with react native.

As a result, this compilation error seems to have emerged:

```
> Task :react-native-blurhash:compileDebugKotlin FAILED

e: /.../react-native-blurhash/android/src/main/java/com/mrousavy/blurhash/BlurhashViewModule.kt: (41, 38): Object is not abstract and does not implement abstract base class member protected/*protected and package*/ abstract fun onFailureImpl(dataSource: DataSource<CloseableReference<CloseableImage!>!>): Unit defined in com.facebook.imagepipeline.datasource.BaseBitmapDataSubscriber
e: /.../react-native-blurhash/android/src/main/java/com/mrousavy/blurhash/BlurhashViewModule.kt: (64, 21): 'onFailureImpl' overrides nothing
```

**Comment by mrousavy** [comment]
Hi! Thanks for the bug report - Does everything work as expected if you simply override that function?

**Comment by beetlebum** [comment]
> Hi! Thanks for the bug report - Does everything work as expected if you simply override that function?

TBH I haven't managed to make it work other than commenting out the whole block.
I'm not too familiar with Kotlin and the code is overriding a Java class so I'm quite confused.

**Comment by beetlebum** [comment]
@mrousavy removing the last `?` seems to do the trick, perhaps the parameter is not nullable anymore.
