### ISSUE TITLE
[FEATURE] Support React Native Fast Image

### ISSUE THREAD

**Issue by naishe** [mrousavy/react-native-blurhash#133]
# Problem

We are working on image heavy educational app. And we use `FastImage` https://github.com/DylanVann/react-native-fast-image extensively. Currently, we wrap the image in a React Native Shimmer placeholder https://github.com/tomzaku/react-native-shimmer-placeholder 

This gives us flexibility to hide shimmer as soon as image load completes and show the image.

I find it much interesting to be able show a matching colored blurhash instead of shimmer. It would be great if blurhash worked with FastImage too.

# Solution

There could be two approaches.
1. *Optional `Image` like `component` attribute:* We can have `component` attribute in `BlurHash` props that should be a `Image`-like component and accepts all the `Image` properties. Like `FastImage` does. And, if the component is passed, it uses that component to render.
2.  *Have a boolean `isVisible` attribute:* Like Shimmer Placeholder, show the blurhash as long as `isVisible` is `true` and show the child component when it is false.

**Describe alternatives you've considered**
I do not have an alternative yet. I was hoping to look into the source code and find where `Image` is used and fork it to give an optional `component` attribute. But I couldn't find.

# Environment

React Native 0.64

**Comment by mrousavy** [comment]
react-native-fast-image uses `UIImageView` on iOS and `AppCompatImageView` on Android to render the Blurhash, this is the fastest way to render an Image. 

The difference between `<Image>` and `<FastImage>` is how image resources (network) get loaded, cached, and re-filled, this has nothing to do with Blurhash. 

For your use-case, consider rethinking the approach: Show a `<Blurhash>` ontop of the `<FastImage>`, and unmount (or fade out) the Blurhash component when the FastImage has loaded. This is how I do it in my apps. :)

Let me know if you have any questions

**Comment by mrousavy** [comment]
>  I was hoping to look into the source code and find where Image is used [...] But I couldn't find.

That's because I am not using React Native's `<Image>` component :) hope my comment above explained why

**Comment by naishe** [comment]
@mrousavy thanks for taking time to clarify this. I love this lib.
