### ISSUE TITLE
Pinned React version

### ISSUE THREAD

**Issue by jakub-gonet** [mrousavy/react-native-blurhash#135]
# Description

It would be nice to be less strict about React version (e.g. ">= 16" or "*"). RN 0.64 uses React 17, this project uses pinned 16.x version, generating conflicts while `npm install`ing it.

https://github.com/mrousavy/react-native-blurhash/blob/b48cceae97f1636dce073366ce6db808543db0ab/package.json#L55

**Comment by mrousavy** [comment]
Hey Jakub! Nice to see you here.

You're right, that version shouldn't be pinned. Could you shoot me a PR? Otherwise I'll fix it next week :)

**Comment by jakub-gonet** [comment]
I tried before submitting this issue but couldn't get the example app to work, sorry.

**Comment by andybui090** [comment]
the same, use yarn add react-native-blurhash is ok, i will wait for new release

**Comment by hfllr** [comment]
Thank you for the quick response @mrousavy 
Strangely enough I get the following error when trying to npm install the latest version of this package:

![Screenshot 2022-02-11 125518](https://user-images.githubusercontent.com/47354807/153588081-28d01462-d967-41cf-a452-9883a97a35b4.png)

**Comment by aprct** [comment]
Running into the same issue above.

Looking forward to the new release! Thanks @mrousavy!
