### ISSUE TITLE
[BUG]Missing kotlinVersion

### ISSUE THREAD

**Issue by hngocl** [mrousavy/react-native-blurhash#138]
# Bug

**Describe the bug**
I install blurhash 1.1.7 then get this error. But work on 1.1.5

**Screenshots**
![image](https://user-images.githubusercontent.com/43195241/144617726-d55b3dee-d3e0-4542-8e9a-fbc35ab735f7.png)

** Proposed solution**
i think you are missing the gradle.properties file on your package
![image](https://user-images.githubusercontent.com/43195241/144618318-949db38f-e483-4b7f-9168-91612075fdea.png)

```json
"react": 17.0.2,
"react-native": 0.66.1,
"react-native-blurhash": 1.1.7
```

**Comment by Yonom** [comment]
I am also experiencing this bug, builds are failing on 1.1.7

**Comment by karim-mohammed** [comment]
I have same bug with me
