### ISSUE TITLE
Are we gonna have support for Expo Go?

### ISSUE THREAD

**Issue by BrodaNoel** [mrousavy/react-native-blurhash#139]
# Question
Regarding this issue: https://github.com/mrousavy/react-native-blurhash/issues/124, are we gonna have that Expo GO support any time soon?
Creating a Custom Expo Go app is not in my plans currently, but I would really like to have something like this in my app.

Is it just a matter of waiting for a couple of new Expo releases? Or we are planing to have it there?

I understand that this question may be more accurate to be asked in Expo project, but first I want to check here if anybody has any information about it.

**Comment by mrousavy** [comment]
You gotta ask that the Expo Go guys 😄
