### ISSUE TITLE
[BUG]Weird glitches on the edges while using zIndex.

### ISSUE THREAD

**Issue by batuhansahan** [mrousavy/react-native-blurhash#171]
I have View same width height border-radius on top of theBlurHash with same width, height  etc.
Blurhash view has also position:absolute zIndex: -1

Corners of the blurhash has weird glitch which is only on physical devices Android, saw it on emulator but on high window size. 

I am wrapping blurhash another view with overflow hidden.

Tested on Samsung s21+, Xiaomi 

![pic](https://user-images.githubusercontent.com/26772801/203493574-4313e183-1003-49be-ab0b-d0599cad28f0.jpg)

react native 0.70.5
react native blur hash: 1.1.10

**Comment by mrousavy** [comment]
Hey! Sorry I don't think I get the issue, are you talking about the weird colors near the corner?

**Comment by mrousavy** [comment]
Does it look correct on iOS?
