### ISSUE TITLE
[BUG] Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'BlurhashModule' could not be found

### ISSUE THREAD

**Issue by robertherber** [mrousavy/react-native-blurhash#186]
# Bug

**Describe the bug**
I'm getting this error when upgrading to version 2.x on Expo 50:
<code>
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'BlurhashModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","SourceCode","Timing","AppState","BlobModule","WebSocketModule","SettingsManager","DevSettings","Networking","RedBox","Appearance","DevLoadingView","DeviceInfo","UIManager","RNCSafeAreaContext","KeyboardObserver","RNCAsyncStorage","NativeAnimatedModule","ImageLoader","I18nManager","LinkingManager"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","BugReporting","HeadlessJsTaskSupport","SoundManager","PlatformLocalStorage","RNC_AsyncSQLiteDBStorage","FrameRateLogger","IntentAndroid","BlurhashModule"]}, js engine: hermes
</code>

Since I guess I don't have any use for the new arch yet while staying managed in Expo I'll stay on v1.x, but I guess it would be nice if things don't break when upgrading.. :)

```json
"react": "18.2.0",
"react-native": "0.73.3",
"react-native-blurhash": "2",
"expo": "~50.0.5",
```

**Comment by Jonatthu** [comment]
It's happening to me as well with same versions

**Comment by ThoaiBuiMCV** [comment]
The same with new version, I am using RN 0.73.4

**Comment by mrousavy** [comment]
cc @janicduplessis is react-native 0.73 supposed to be supported?

**Comment by janicduplessis** [comment]
Yes, it should work, it is the version I tested on. Does that happen on ios or android (or both)?

Just to make sure did you try a clean build?

**Comment by Jonatthu** [comment]
@janicduplessis I did a clean build with 
 "react-native": "0.73.4",
 "expo": "^50.0.6",
 "react-native-blurhash": "2.0.0",

**Comment by ThoaiBuiMCV** [comment]
@janicduplessis, I did try reinstall node_module and remove iOS build and pod, the result still exist, I am using RN CLI
 "react-native": "0.73.4",
"react-native-blurhash": "2.0.0",

**Comment by iwater** [comment]
+1

**Comment by Martin2037** [comment]
+1

**Comment by janicduplessis** [comment]
Just to confirm this is using managed expo right? So it used to work in v1 when the native code is not available?

**Comment by nicolofranceschi** [comment]
+1

**Comment by iM-GeeKy** [comment]
I think this may need to be reopened. I tried updating to the latest version `2.0.1` and received the following when building on Expo servers via `eas build` using `"react-native": "0.73.4",` and `"expo": "~50.0.8",`.

```
› Compiling react-native-blurhash Pods/react-native-blurhash » react-native-blurhash-dummy.m

› Compiling react-native-blurhash Pods/react-native-blurhash » BlurhashViewManager.m

› Compiling react-native-blurhash Pods/react-native-blurhash » BlurhashViewComponentView.mm

› Compiling react-native-blurhash Pods/react-native-blurhash » BlurhashModule.mm

▸ ** BUILD FAILED **
```

and prior to building, I just tried to update to `2.0.1` and received the following. 

![simulator_screenshot_DBEB72B1-F7A7-443F-AC7E-977F95A59199](https://github.com/mrousavy/react-native-blurhash/assets/7604441/b15b855a-ba99-4355-be49-2fab2eea732f)

**Comment by janicduplessis** [comment]
@iM-GeeKy Is there more logs? I don’t see the actual error.

**Comment by iM-GeeKy** [comment]
> @iM-GeeKy Is there more logs? I don’t see the actual error.

The screenshot may be misleading b/c I didn't not rebuild my expo project (which I may have needed to). The fact that it fails to build is probably a better source of truth.

**Comment by sektr63a** [comment]
Faced with this error while run a build
@janicduplessis 

![image](https://github.com/mrousavy/react-native-blurhash/assets/4604578/04998cfb-6b73-46fa-882c-114b583a3516)

**Comment by baselshlewett** [comment]
I got the same issue on iOS

versions
react-native: 0.73.5
react-native-blurhash: ^2.0.1
