### ISSUE TITLE
[BUG] Blurhash.encode crash in ios 0.75.2 by new architecture

### ISSUE THREAD

**Issue by llr101** [mrousavy/react-native-blurhash#197]
# Bug

**Describe the bug**

Blurhash.encode crash in ios 0.75.2 by new architecture

**To Reproduce**
Blurhash.encode a local image

**Expected behavior**

**Screenshots**

**(Optional) Proposed solution**
If you have an idea on how one might fix this bug, please describe it here.

# Environment

**Additional context**

```
paste the output of `react-native info` here
```

```json
"react": PASTE_VERSION_HERE,
"react-native": PASTE_VERSION_HERE,
"react-native-blurhash": PASTE_VERSION_HERE
```

**Comment by llr101** [comment]
"react": 18.3.1,
"react-native": 0.75.2,
"react-native-blurhash": 2.0.3

react native use new architecture

![14fb5e779fca64edf0f3620c0928beb7](https://github.com/user-attachments/assets/17a87689-95ab-4b1c-b00b-6d463e729482)

**Comment by mrousavy** [comment]
maybe that needs to be NSNumber* instead of double

**Comment by llr101** [comment]
@mrousavy I tried, no crash, but no resolve or reject callback in react native. I can’t get image hash

**Comment by llr101** [comment]
![ef7e1179ccfd255a88afa61c0216b6ad](https://github.com/user-attachments/assets/05556bda-3d2e-4488-bcac-c2c030186558)

**Comment by llr101** [comment]
When I call Blurhash.code, the xcode log show, and no resolve or reject callback:
![ef7e1179ccfd255a88afa61c0216b6ad](https://github.com/user-attachments/assets/6030cd56-0eab-49aa-87bd-2836f5ad796e)

**Comment by llr101** [comment]
@mrousavy It seems like codegen generate a file with wrong params name and type. #198
