### ISSUE TITLE
resizeMode on Android not working

### ISSUE THREAD

**Issue by mrousavy** [mrousavy/react-native-blurhash#5]
On Android the `resizeMode` prop does not work.

This is because the differences in structure, on iOS I create a `UIImage` and display that. On Android I create a `Bitmap`, convert that to a `BitmapDrawable` and then set that as the background of the `ReactImageView`!

I need to find a different way to set the image on android.

**Comment by Stevemoretz** [comment]
Hi any news about this?

**Comment by Stevemoretz** [comment]
Also resize mode `contain` doesn't work well on iOS it does exactly what cover does.
