### ISSUE TITLE
[FEATURE] Support encoding for local image files

### ISSUE THREAD

**Issue by mrousavy** [mrousavy/react-native-blurhash#75]
# Problem

Currently there is no way to encode a local image file (photo) to a blurhash. You have to use a third party library to read it, which passes a huge base64 string over the Bridge, then pass that to the `Blurhash.encode(...)` function, which, again, goes over the bridge. This is a big waste of time.

# Solution

Instead, pass local file paths (`/var/...`, or `ph://` protocol) to the `Blurhash.encode(...)` function, which gets read natively, saving a lot of performance and not stressing the JS thread + Bridge.

**Comment by mrousavy** [comment]
Basically I need to try to read it using the RCTImageLoader

* [iOS](https://github.com/mrousavy/react-native-blurhash/blob/master/ios/BlurhashViewManager.swift#L27-L67)
* [Android](https://github.com/mrousavy/react-native-blurhash/blob/master/android/src/main/java/com/mrousavy/blurhash/BlurhashViewModule.kt#L30-L44)

**Comment by pontusab** [comment]
Oh yeah, it worked, but it takes a prox ~12s for a 1500x1500px image to get encoded. Is that normal?

**Comment by mrousavy** [comment]
@pontusab yes, the algorithm takes about that long for such a big image. Either try resizing the image to a way smaller size (100x100 is fine) using a resize lib, or encode it server-side using the blurhash C implementation (I've done that, works perfectly).

**Comment by pontusab** [comment]
Thanks, man! I'll do it in our image service instead, but will use this for render 🥇

**Comment by benjamin-r-erb** [comment]
@mrousavy Thanks so much for your work on this -- trying to use the encoding function and getting a type error. This is occurring with both a local uri as well as the example listed on blurha.sh . Any thought on what I'm missing?

Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'createBlurhashFromImage' of undefined
TypeError: Cannot read property 'createBlurhashFromImage' of undefined

uri for local image: file:///Users/benjaminerb/Library/Developer/CoreSimulator/Devices/FAC4A76D-A3CA-4EE4-A911-EACEB98744C2/data/Containers/Data/Application/83BAE5C7-E7EB-4DAE-A039-96791230E89A/Library/Caches/ExponentExperienceData/%2540benjamin.erb%252Fdough/ImageManipulator/F06596AA-4FA1-4586-8D12-D4ED13F84BC1.jpg

console.log('icon uri:', iconObject.uri)
const blurhash = await Blurhash.encode(iconObject.uri, 4, 3);

Same uri displays image using image component.

Thanks,
Ben

**Comment by mrousavy** [comment]
@benjamin-r-erb did you install pods? `cd ios && pod install`

**Comment by benjamin-r-erb** [comment]
> @benjamin-r-erb did you install pods? `cd ios && pod install`

Thanks @mrousavy Ah...so, that's the issue. I'm using Expo. I believe that I read that this is incompatible with Expo currently. Any plans to support it or easy work-around for the encoding?

**Comment by mrousavy** [comment]
No, this is a native module and will not work with expo because it requires native code.

**Comment by benjamin-r-erb** [comment]
> No, this is a native module and will not work with expo because it requires native code.

Thank you, @mrousavy  -- I appreciate the quick reply and clarification.

**Comment by mrousavy** [comment]
Closing this as it is now possible to provide the same URIs to `Blurhash.encode` as in the `<Image source={{ uri: ` property.
