### ISSUE TITLE
[QUESTION] Is it possible to disable logs in the console?

### ISSUE THREAD

**Issue by ku8ar** [mrousavy/react-native-blurhash#91]
# Question

Amazing library. It works great in our application. We only have one problem: information noise.

We use blurhash in items on FlatList, so we generate a lot of them.
Is it possible to run some silent mode so that the console is not spammed with these logs?

<img width="945" alt="Zrzut ekranu 2020-11-10 o 16 56 49" src="https://user-images.githubusercontent.com/16975059/98698401-4410d900-2376-11eb-80b9-8f953a9dbe29.png">

**Comment by mrousavy** [comment]
Hi! Sorry for the late response, I somehow was unsubscribed from my own repository 🤨 

Regarding the actual issue, I also noticed that I still left the debug log statements in there. I've already removed them on the master branch but didn't publish a new version yet, will do that right now!

**Comment by mrousavy** [comment]
Fixed with 1.0.28 ✅

**Comment by ku8ar** [comment]
thanks!
